analyzer:
  exclude:
    - "lib/**/*.g.dart"
    - "lib/**/*.freezed.dart"
    - "lib/generated/**/*.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_return: error
    missing_required_param: error
    invalid_use_of_visible_for_testing_member: error
    invalid_use_of_protected_member: error
    invalid_override_of_non_virtual_member: error
    unused_field: error
    unused_local_variable: error
    unused_import: error # there may be false positives - see https://github.com/dart-lang/sdk/issues/39263
    unused_element: error
    override_on_non_overriding_member: error
    annotate_overrides: error
    await_only_futures: error
    unawaited_futures: error
    camel_case_types: error
    cancel_subscriptions: error
    close_sinks: error
    comment_references: error
    constant_identifier_names: error
    control_flow_in_finally: error
    empty_statements: error
    avoid_types_on_closure_parameters: error
    unnecessary_const: error
    avoid_positional_boolean_parameters: error
    avoid_return_types_on_setters: error
    unnecessary_brace_in_string_interps: error
    unnecessary_lambdas: error
    prefer_mixin: error
    prefer_final_fields: error
    unnecessary_new: error
    prefer_final_locals: error
    unnecessary_this: info
    avoid_init_to_null: info
    always_use_package_imports: info
    avoid_relative_lib_imports: info
    prefer_initializing_formals: info
    prefer_collection_literals: info
    omit_local_variable_types: info
    prefer_expression_function_bodies: info
    prefer_null_aware_operators: info

linter:
  rules:
    - always_use_package_imports
    - annotate_overrides
    - avoid_relative_lib_imports
    - await_only_futures
    - unawaited_futures
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - constant_identifier_names
    - control_flow_in_finally
    - empty_statements
    - avoid_types_on_closure_parameters
    - unnecessary_const
    - avoid_positional_boolean_parameters
    - avoid_return_types_on_setters
    - unnecessary_brace_in_string_interps
    - unnecessary_this
    - unnecessary_lambdas
    - avoid_init_to_null
    - omit_local_variable_types
    - prefer_mixin
    - prefer_final_fields
    - unnecessary_new
    - prefer_initializing_formals
    - prefer_collection_literals
    - prefer_final_locals
    - prefer_expression_function_bodies
    - prefer_null_aware_operators
